add_newline = false

[git_branch]
symbol = "ğŸŒ± "

[character]
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"

[shlvl]
disabled = false

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "
